// ~Hack~ Newer Super Mario Bros. Wii
// #ID = 34904

level_images = {
    0x00: "1-1 Palm Beach",
    0x01: "1-2 Yoshi Woods",
    0x02: "1-3 Springwater Swamp",
    0x03: "1-4 Growing Greenwood",
    0x04: "1-5 Fuzzy Canyon",
    0x05: "1-6 Rainshed Pond",
    0x06: "1-7 Tangle Temple",
    0x07: "1-8 Switch Shift Groove",
    0x0e: "1-Tower: Timber Tower",
    0x18: "1-Castle: Creepcrack Castle",
    0x1e: "Yellow Switch Palace",
    0x20: "Challenge House A",
    0x25: "1-Airship: Derelict Airship",
    0x28: "Yoshi House",
    0x100: "2-1 Cactus Cove",
    0x101: "2-2 Gushing Gutter",
    0x102: "2-3 Dripdrop Drains",
    0x103: "2-4 Cascade Chasm",
    0x104: "2-5 Barrelband Wilds",
    0x105: "2-6 Urchin Seasands",
    0x106: "2-7 Windworn Dunes",
    0x107: "2-8 Searing Sands",
    0x108: "2-9 Pillar Pass",
    0x109: "2-A Fossil Tunnel",
    0x10e: "2-Tower Pipeline Tower",
    0x118: "2-Castle: Pyramid Castle",
    0x120: "Challenge House B",
    0x121: "Desert Music House",
    0x125: "2-Airshpip: Sandship",
    0x200: "3-1 Chomproller Heights",
    0x201: "3-3 Butterwood Crossing",
    0x202: "3-2 Grimymole Mine",
    0x203: "3-4 Wobbleshroom Bluffs",
    0x204: "3-5 Fungi Pit",
    0x205: "3-6 Bubble Basin",
    0x206: "3-7 Slanty Shroomroad",
    0x20e: "3-Tower: Burnblaze Tower",
    0x218: "3-Castle: Moltenwire Castle",
    0x220: "Challenge House C",
    0x221: "Mushroom Music House",
    0x225: "3-Airship: Capshroom Airship",
    0x300: "4-1 Bamboo Steppes",
    0x301: "4-2 Flipblock Orchard",
    0x302: "4-3 Cherry Falls",
    0x303: "4-4 Petal Lake",
    0x304: "4-5 Vine Chasm",
    0x305: "4-A Hilltop Town", 
    0x306: "4-6 Rooftop Hop",
    0x30e: "4-Tower: Blossom Tower",
    0x318: "4-Castle: Samurai Castle",
    0x31e: "The Green Switch Palace",
    0x320: "Challenge House D",
    0x321: "Village Music House",
    0x325: "Nutscrew Airship",
    0x400: "5-1 Snowfield Tundra",
    0x401: "5-2 Snowball Field",
    0x402: "5-3 Frosty Highlands",
    0x403: "5-4 Frostbite Ridge",
    0x404: "5-5 Snowfall Peak",
    0x405: "5-6 Molten Icelifts",
    0x406: "5-7 Penguin Heatbath",
    0x407: "5-A Lavafrost Cavern",
    0x408: "5-8 Magma Iceburrow",
    0x409: "5-9 Glacier Lavalake",
    0x40e: "5-Tower: Crystalfrost Tower",
    0x418: "5-Castle: Chillsear Castle",
    0x421: "Frosty Music House",
    0x425: "5-Airship: Snowdrift Airship",
    0x500: "6-1 Bonechill Shaft",
    0x501: "6-2 Pumpkin Road",
    0x502: "6-3 Fog Cemetary",
    0x503: "6-4 Glowlit Manor",
    0x504: "6-5 Moonlit Woods",
    0x505: "6-6 Cawcaw Treeway",
    0x506: "6-A Colossus House",
    0x507: "6-7 Drenched Gloomlake",
    0x508: "6-8 Buried Boneyard",
    0x50e: "6-Tower: Spookloft Tower",
    0x518: "6-Castle: Delusion Castle",
    0x525: "6-Airship: Shipwreck Galleon",
    0x520: "Chalenge House E",
    0x600: "7-1 Shy Guy Peaks",
    0x601: "7-2 Paratroopa Peaks",
    0x602: "7-3 Beanstalk Ascent",
    0x603: "7-4 Spacedust Heap",
    0x604: "7-5 Asteroid Belt",
    0x605: "7-6 Spintop Nebula",
    0x606: "7-7 Star Haven",
    0x607: "7-8 Starfruit Garden",
    0x60e: "7-Tower: Electron Tower",
    0x618: "7-Castle: Novastar Castle",
    0x61e: "The Blue Switch Palace",
    0x620: "Challenge House F",
    0x625: "7-Airship: Spaceship Koopa",
    0x700: "8-1 Batallion Frontier",
    0x701: "8-2 Jet Airship",
    0x702: "8-4 Molten Airship",
    0x703: "8-3 Burnstone Flowfalls",
    0x704: "8-Train: Underground Railroad",
    0x705: "8-6 Volcano Rapids",
    0x706: "8-7 Magmaworks Factory",
    0x707: "8-A Dragonride Firesea",
    0x708: "8-8 Eruption Crater",
    0x709: "8-9 Ironworks Forge",
    0x70e: "8-Tower: Factory Tower",
    0x70f: "8-Tower-2: Pendulum Tower",
    0x717: "8-Castle: Bowser's Keep",
    0x718: "8-Castle-2: Bowser's Castle",
    0x720: "Challenge House G",
    0x800: "9-1 Red Lava",
    0x801: "9-2 Brown Forest",
    0x802: "9-3 Orange Prairie",
    0x803: "9-4 Yellow Beach",
    0x804: "9-5 Mossdeep Greens",
    0x805: "9-6 Blue Chilldesert",
    0x806: "9-7 Navyblue Molemine",
    0x807: "9-8 Purple Sewer",
    0x808: "9-9 Grey Mountains",
    0x809: "9-10 Black Clappers",
    0x900: "A-1 Autumn Plateau",
    0x901: "A-2 Appletree Woods",
    0x902: "A-3 Fall Harvest",
    0x903: "A-A Goldbuzz Forest",
    0x904: "A-Fortress: Leafpile Fortress",
    0x905: "B-1 Mighty Meadow",
    0x906: "B-2 Pintsized Plains",
    0x907: "B-3 Troopashell Track",
    0x908: "B-4 Cheepcheep Creek",
    0x909: "B-Fortress: Formmidable Fortress",
    0x90a: "D-1 Swooper Cellar",
    0x90b:"D-2 Toxic Wigglershaft",
    0x90c: "D-3 Spine Springs",
    0x90d: "D-A Carapace Catacomb",
    0x90e: "D-Fortress: Toxic Fortress",
    0x90f: "E-1 Bombshell Bridge",
    0x910: "E-2 Fallout Footbridge",
    0x911: "E-3 Bombassault Gorge",
    0x912: "C-1 Manta Raid",
    0x915: "C-2 Nimbus Highway",
    0x916: "C-3 Parabeetle Peril",
    0x917: "C-4 Sprocket Skies",
    0x918: "C-Tower: Clockwork Tower",
    0x91e: "The Red Switch Palace",
    0x921: "Challenge House H",
    0x922: "Minimega Music House",
    0x923: "Crystal Music House",
    0x924: "Goldwood Music House"
    
}


/* Save States
W1: A lot of W1
W1-2: A lot of RAM address finding
WA:
    1: Start
    2: Spring shenanigans
    3: Berries in A-2
    4: Music House


W2:
    1: 2-3
    2: Challenge House B
    3: 2-6
    4: Desert Music House
    5: chal-3
    6: music 3
    7: random
    8: after green palace
    9: Challenge House D
    10: in green palace

W4:
    1: Village Music House
    2: 2-Fortress boss
    3: 5-4 pick a path
    4: Red Switch
    5: 5-Tower boss
    6: Frosty Music House
    7: Challenge House E
    8: Haunted Music House
    9: blue switch
4-4 get 3rd star coin without green blocks
7-1: complete secret exit without blue switch
7-castle has 2 red rings

W8: 
    1: idk
    2: 8-tower
    3-6: Random stuff
    7: Rollercoaster level
    8: Outside Bowser's Keep
    9: Outside final boss

WB C D:
    Unordered
    8: Last stage in special world
Notes about coinless run
1-Tower 1 coin run
1-Airship seems like a good challenge
2-2 seems quite hard
2-7 is the sandstorm level, could be fun
3-7 seems challenging if propeller restricted
4-Tower minimum coin run without propeller?


*/
level_image=word_be(0x00315b9c)
level_status=byte(0x00354ee7)

file_selected=byte(0x00c7f7c6)

level_data_start = 0x00c7fecf


title_screen = byte(0x00315b9b)
function not_on_title_screen() => title_screen == 0x00

p1_lives = byte(0x00354e93)
p2_lives = byte(0x00354e94)
p3_lives = byte(0x00354e95)
p4_lives = byte(0x00354e96)

coins = byte(0x00354ea3)

overworld_map = byte(0x00c7fe63) // File 1

overworld_position = byte(0x00c7fe65) // File 1

class item_reserve{ // File 1
    m = byte(0x00c7fe69 + 0x980*file_selected)
    ff = byte(0x00c7fe6a + 0x980*file_selected)
    pr = byte(0x00c7fe6b + 0x980*file_selected)
    ic = byte(0x00c7fe6c + 0x980*file_selected)
    pe = byte(0x00c7fe6d + 0x980*file_selected)
    mm = byte(0x00c7fe6e + 0x980*file_selected)
    s = byte(0x00c7fe6f + 0x980*file_selected)
    h = byte(0x00c7fe70 + 0x980*file_selected)
    
    function change(num){
        return m+ff+pr+ic+pe+mm+s+h - prev(m)+prev(ff)+prev(pr)+prev(ic)+prev(pe)+prev(mm)+prev(s)+prev(h) == num
    }
}

death_start = 0x00c80624 // File 1


hard_mode = byte(0x00e5740c)
function in_hard_mode() => hard_mode==1

debug_mode = byte(0x00e69fc8) //doesn't affect gameplay in a meaningful way
function in_debug_mode() => debug_mode==1 

berries = byte(0x15319c3)

timer = word_be(0x01547d42)
score = dword_be(0x01547d48)

powerup = byte(0x0154d427)

mario_x = dword_be(0x0154d470)
mario_y = dword_be(0x0154d474)

on_ground = byte(0x0154d4ab)
parabeetles = byte(0x015e67ff)

//given a level_image, retrieve the address that the data is stored in for the current file
//example: level 0x221
//level = 0x221%0x100 = 0x21
//world = 0x221/0x100 = 0x02
//byte = world * 0x2a*4 + level*4 + 0x00c7fecf = 2 * 0x2a + 21 0x00c7fecf = 0x00c800a3 
// (*4 since each level data section is 4 bytes)
function get_level_data(level_img){
    level=level_img%0x100
    world=level_img/0x100
    return world*0x2a*4 + level*4 + level_data_start + 0x980*file_selected
}


// * * * * * * * * * * * * * * * STANDARD PROGRESSION * * * * * * * * * * * * * * * \\

// Levels that you are required to beat (that should have achievements): 
// 3-Airship, 7-Airship, Bowser's Castle, Bowser's Keep (w)
// Levels that I want an achievement for:
// 1-Airship, 2-Airship, 4-Airship, 5-Airship, 6-Airship, 9-10, 
// maybe the final level in the lettered worlds, idk

// format: key : [title, description, points, type_flag]
Boss_Achievements = {
    0x25: ["Iggy Is Die", "Defeat Iggy Koopa in 1-Airship: Derelict Airship", 5, ""],
    0x125: ["What boss is this 2", "Defeat  in 2-Airship: Sandship", 5, ""],
    0x225: ["What boss is this 3", "Defeat  in 3-Airship: Capshroom Airship", 5, ""],
    0x325: ["What boss is this 4", "Defeat  in 4-Airship: Nutscrew Airship", 5, ""],
    0x425: ["What boss is this 5", "Defeat  in 5-Airship: Snowdrift Airship", 5, ""],
    0x525: ["What boss is this 6", "Defeat  in 6-Airship: Shipwreck Galleoun", 5, ""],
    0x625: ["What boss is this 7", "Defeat  in 7-Airship: Spaceship Koopa", 10, ""],
    0x717: ["What boss is this 8-Keep", "Defeat  in 8-Castle: Bowser's Keep", 10, ""],
    0x718: ["What boss is this 8-Castle", "Defeat  in 8-Castle: Bowser's Castle", 10, ""],
}
// If the level ends in a flag, must use this dict instead
Level_Achievements = {
    0x809: ["Newer Super Special World Wii", "Complete World 9-10: Black Cappers, and complete every exit in the game!", 25, ""]
}

for key in Boss_Achievements{
    achievement(
        title=Boss_Achievements[key][0],
        description=Boss_Achievements[key][1],
        points=Boss_Achievements[key][2],
        type=Boss_Achievements[key][3],
        trigger= level_image==key && level_status==0x05 && prev(level_status)!=level_status
    
    )
}

for key in Level_Achievements{
    achievement(
        title=Level_Achievements[key][0],
        description=Level_Achievements[key][1],
        points=Level_Achievements[key][2],
        type=Level_Achievements[key][3],
        trigger= level_image==key && level_status==0x02 && prev(level_status)==0x01
    
    )
}


// * * * * * * * * * * * * * * * STAR COINS * * * * * * * * * * * * * * * \\

// Want these to be separated by world, simple enough, just have to deal with some addressing
// format: key: [[title, description, points], [level1, level2, ...]]
// 15 total 5, 5, 5, 10, 10, 10, 10, 25, 25 [every star coin], 3, 3, 3, 3, 3
Star_Coins = {
    0x01: [["W-1 Star Coins", "Collect all Star Coins in Yoshi's Island", 5], 
            [0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x0e, 0x18, 0x25]],
    0x02: [["W-2 Star Coins", "Collect all Star Coins in Rubble Ruins and Soggy Sewers", 5], 
            [0x100, 0x101, 0x102, 0x103, 0x104, 0x105, 0x106, 0x107, 0x108, 0x109, 0x10e, 0x119, 0x125]],
    0x03: [["W-3 Star Coins", "Collect all Star Coins in Mushroom Peaks", 5], 
            [0x200, 0x201, 0x202, 0x203, 0x204, 0x205, 0x206, 0x20e, 0x218, 0x225]],
    0x04: [["W-4 Star Coins", "Collect all Star Coins in Sakura Village", 10], 
            [0x300, 0x301, 0x302, 0x303, 0x304, 0x305, 0x306, 0x30e, 0x318, 0x325]],
    0x05: [["W-5 Star Coins", "Collect all Star Coins in Freezeflame Glavier and Freezeflame Volcano", 10], 
            [0x400, 0x401, 0x402, 0x403, 0x404, 0x405, 0x406, 0x407, 0x408, 0x409, 0x40e, 0x418, 0x425]],
    0x06: [["W-6 Star Coins", "Collect all Star Coins in Pumpkin Boneyard", 10], 
            [0x500, 0x501, 0x502, 0x503, 0x504, 0x505, 0x506, 0x507, 0x508, 0x50e, 0x518, 0x525]],
    0x07: [["W-7 Star Coins", "Collect all Star Coins in Sky Mountain and Starry Skies", 10], 
            [0x600, 0x601, 0x602, 0x603, 0x604, 0x605, 0x606, 0x607, 0x60e, 0x618, 0x625]],
    0x08: [["W-8 Star Coins", "Collect all Star Coins in Koopa Planet and Koopa Core", 25], 
            [0x700, 0x701, 0x702, 0x702, 0x703, 0x704, 0x705, 0x706, 0x707, 0x708, 0x709, 0x70e, 0x70f, 0x717, 0x718]],
    0x09: [["W-9 Star Coins", "Collect all Star Coins in Bonus Land", 25], 
            [0x800, 0x801, 0x802, 0x803, 0x804, 0x805, 0x806, 0x807, 0x808, 0x809]],
    0x0a: [["W-A Star Coins", "Collect all Star Coins in Goldwood Forest", 3], 
            [0x900, 0x901, 0x902, 0x903]],
    0x0b: [["W-B Star Coins", "Collect all Star Coins in Mighty Meadow", 3], 
            [0x905, 0x906, 0x907, 0x908, 0x909]],
    0x0c: [["W-C Star Coins", "Collect all Star Coins in Sky City", 3], 
            [0x912, 0x915, 0x916, 0x917, 0x918]],
    0x0d: [["W-D Star Coins", "Collect all Star Coins in Crystal Caves", 3], 
            [0x90a, 0x90b, 0x90c, 0x90d, 0x90d]],
    0x0e: [["W-E Star Coins", "Collect all Star Coins in Bombard Cliffs", 3], 
            [0x90f, 0x910, 0x911]],
}

function Star_Coin_Logic(Star_Coin){
    return bit0(get_level_data(Star_Coin)) +
            bit1(get_level_data(Star_Coin)) +
            bit2(get_level_data(Star_Coin)) 
}

function Prev_Star_Coin_Logic(Star_Coin){
    return prev(bit0(get_level_data(Star_Coin))) +
            prev(bit1(get_level_data(Star_Coin))) +
            prev(bit2(get_level_data(Star_Coin))) 
}

for key in Star_Coins{
    achievement(
        title=Star_Coins[key][0][0],
        description=Star_Coins[key][0][1],
        points=Star_Coins[key][0][2],
        trigger = measured(
            sum_of(
                Star_Coins[key][1],
                Star_Coin_Logic
            ) == length(Star_Coins[key][1])*3
        ) &&         
        sum_of(
            Star_Coins[key][1],
            Prev_Star_Coin_Logic
        ) == length(Star_Coins[key][1])*3-1
         
    )
}

// * * * * * * * * * * * * * * * EXITS * * * * * * * * * * * * * * * \\

// Incredibly similar to the above, except there are also secret exits to worry about
// format: key: [[title, description, points], [normalexit1, normalexit2, ...], [secretexit1, secretexit2, ...]]
// Separated by worlds, W9 does not get one
// 1, 2, 3, 4, 5, 6, 7, 8, A, B, C, D, E = 13 total
function Get_Exit(lvl_img){
    return bit4(get_level_data(lvl_img))
}
function Prev_Get_Exit(lvl_img){
    return prev(bit4(get_level_data(lvl_img)))
}
function Get_Secret_Exit(lvl_img){
    return bit5(get_level_data(lvl_img))
}
function Prev_Get_Secret_Exit(lvl_img){
    return prev(bit5(get_level_data(lvl_img)))
}

exits = {
    0x01: [["W1 Clear", "Get all the exits in Yoshi's Island", 5], 
    [0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x0e, 0x18, 0x25], [0x05, 0x07]],
}

for world in exits{
    achievement(
        title= exits[world][0][0],
        description = exits[world][0][1],
        points = exits[world][0][2],
        trigger = 
            measured(
                sum_of(
                exits[world][1], Get_Exit 
                ) +
                sum_of(
                    exits[world][2], Get_Secret_Exit
                ) == length(exits[world][1])+length(exits[world][2])
            ) &&
            sum_of(
                exits[world][1], Prev_Get_Exit 
                ) +
            sum_of(
                exits[world][2], Prev_Get_Secret_Exit
            ) == length(exits[world][1])+length(exits[world][2])-1
    )
}


// * * * * * * * * * * * * * * * CHALLENGES * * * * * * * * * * * * * * * \\

/* MISSING CODE NOTES:
    Getting all 4 items in a Music House {Can possibly be circumvented by performing a delta on the item reserves}
    Mario Actions
        Sliding as a penguin
        Using propeller spin {powerup and item}
        Jumping (for minimum jumps challenges)
    sublevel screen (i.e., identifier between main part of level and bonus screen thru pipe that contains 3 1-ups)
    Starting a level from a checkpoint
    Some sort of flag signifying a 1-up mushroom has been collected (excludes combo 1-ups and coin 1-ups)
        - Would prefer to not have this based on a player's 1-up count since there's many ways to trigger that, 
        + when you have 99 the counter doesn't go up anymore
    Parabeetles spawn a 1-up
    In Credits flag
    
//Hard mode achievements
// Levels for this have not been picked
// Coding difficulty: Easy

//Debug mode
// Just turn it on
// Coding difficulty: Easy

//Challenge Houses
// 2 achievements, complete any challenge house, complete all 8 challenge houses
// Coding difficulty: Easy
// Level addresses: 0x921, 0x720, 0x620, 0x520, 0x320, 0x220, 0x120, 0x20

//Music Houses
// [missable]
// 1 achievement per music houses, 7 total
// 5 points each
// Coding difficulty: Medium {Missing Code Notes}

//Coins
// Collect x coins in y level
// variable amount of points
// 8-Train, 5-Tower, 2-5 (min-spins) {}
// Coding difficulty: Medium/Hard {may rely on other address, like credits scene signifier}

//Hammer Mario
// Coding difficulty: easy

//Collect specific 1-ups
// 4-4, 6-Castle, D-2
// Coding difficulty: Hard (may have to rely on tracking specific 1-ups.)

//99 lives
// Coding difficulty: easy

//Low score
// C-4 (no checkpoint or propeller), E-3
// Coding difficulty: easy

//Damageless
// A-Tower, B-Tower, C-Tower etc, W5 boss, Final bowser and maybe mid-W8 fight
// Coding difficulty: easy

//Red Rings
// 5-4 is for some reason the only one I have listed
// Coding difficulty: TBD

//All Berries
// A-2
// Coding difficulty: easy

//Speedrun
// 2-9, 6-Tower boss, maybe something in W9 (Full world speedrun?)
// Coding difficulty: Medium (Hard for W9 speedrun)

//Other
// 2-A fly over the level (Medium Difficulty)
// 1-up combo in E-1 (TBD)
// 5-1 penguin slide (Hard)
// 7-1 without blue switch (Easy)
// 7-? min jumps (Hard)
// 8-2 all star coins no propeller or checkpoint (Medium)
// B-1 Mighty Meadow as Mini Mario [m] (Easy)
// Complete challenge house as Mini Mario [1p] [m] (Easy)
// C-Tower super hidden room [Medium]
// Spawning x lives in the parabeetle level (don't remember which one that is) [Hard]

*/
// * * * * * * * * * * * * * * * RICH PRESENCE * * * * * * * * * * * * * * * \\
rich_presence_display("Stage {0} | Lives {1} | 💀 {2} | {3}",
    rich_presence_value("stage", byte(0xC7FE65)),
    rich_presence_value("lives", word(0x354E93)),
    rich_presence_value("death", tally(0, prev(byte(0x354E93)) > byte(0x354E93), always_false())),
    rich_presence_value("score", dword_be(0x1547D48), format="SCORE")
)


