// ~Hack~ Newer Super Mario Bros. Wii
// #ID = 34904

level_images = {
    0x00: "1-1 Palm Beach",
    0x01: "1-2 Yoshi Woods",
    0x02: "1-3 Springwater Swamp",
    0x03: "1-4 Growing Greenwood",
    0x04: "1-5 Fuzzy Canyon",
    0x05: "1-6 Rainshed Pond",
    0x06: "1-7 Tangle Temple",
    0x07: "1-8 Switch Shift Groove",
    0x0e: "1-Tower: Timber Tower",
    0x18: "1-Castle: Creepcrack Castle",
    0x1e: "Yellow Switch Palace",
    0x20: "Challenge House A",
    0x25: "1-Airship: Derelict Airship",
    0x28: "Yoshi House",
    0x100: "2-1 Cactus Cove",
    0x101: "2-2 Gushing Gutter",
    0x102: "2-3 Dripdrop Drains",
    0x103: "2-4 Cascade Chasm",
    0x104: "2-5 Barrelband Wilds",
    0x105: "2-6 Urchin Seasands",
    0x106: "2-7 Windworn Dunes",
    0x107: "2-8 Searing Sands",
    0x108: "2-9 Pillar Pass",
    0x109: "2-A Fossil Tunnel",
    0x10e: "2-Tower Pipeline Tower",
    0x118: "2-Castle: Pyramid Castle",
    0x120: "Challenge House B",
    0x121: "Desert Music House",
    0x125: "2-Airshpip: Sandship",
    0x200: "3-1 Chomproller Heights",
    0x201: "3-3 Butterwood Crossing",
    0x202: "3-2 Grimymole Mine",
    0x203: "3-4 Wobbleshroom Bluffs",
    0x204: "3-5 Fungi Pit",
    0x205: "3-6 Bubble Basin",
    0x206: "3-7 Slanty Shroomroad",
    0x20e: "3-Tower: Burnblaze Tower",
    0x218: "3-Castle: Moltenwire Castle",
    0x220: "Challenge House C",
    0x221: "Mushroom Music House",
    0x225: "3-Airship: Capshroom Airship",
    0x300: "4-1 Bamboo Steppes",
    0x301: "4-2 Flipblock Orchard",
    0x302: "4-3 Cherry Falls",
    0x303: "4-4 Petal Lake",
    0x304: "4-5 Vine Chasm",
    0x305: "4-A Hilltop Town", 
    0x306: "4-6 Rooftop Hop",
    0x30e: "4-Tower: Blossom Tower",
    0x318: "4-Castle: Samurai Castle",
    0x31e: "The Green Switch Palace",
    0x320: "Challenge House D",
    0x321: "Village Music House",
    0x325: "Nutscrew Airship",
    0x400: "5-1 Snowfield Tundra",
    0x401: "5-2 Snowball Field",
    0x402: "5-3 Frosty Highlands",
    0x403: "5-4 Frostbite Ridge",
    0x404: "5-5 Snowfall Peak",
    0x405: "5-6 Molten Icelifts",
    0x406: "5-7 Penguin Heatbath",
    0x407: "5-A Lavafrost Cavern",
    0x408: "5-8 Magma Iceburrow",
    0x409: "5-9 Glacier Lavalake",
    0x40e: "5-Tower: Crystalfrost Tower",
    0x418: "5-Castle: Chillsear Castle",
    0x421: "Frosty Music House",
    0x425: "5-Airship: Snowdrift Airship",
    0x500: "6-1 Bonechill Shaft",
    0x501: "6-2 Pumpkin Road",
    0x502: "6-3 Fog Cemetary",
    0x503: "6-4 Glowlit Manor",
    0x504: "6-5 Moonlit Woods",
    0x505: "6-6 Cawcaw Treeway",
    0x506: "6-A Colossus House",
    0x507: "6-7 Drenched Gloomlake",
    0x508: "6-8 Buried Boneyard",
    0x50e: "6-Tower: Spookloft Tower",
    0x518: "6-Castle: Delusion Castle",
    0x525: "6-Airship: Shipwreck Galleon",
    0x520: "Chalenge House E",
    0x600: "7-1 Shy Guy Peaks",
    0x601: "7-2 Paratroopa Peaks",
    0x602: "7-3 Beanstalk Ascent",
    0x603: "7-4 Spacedust Heap",
    0x604: "7-5 Asteroid Belt",
    0x605: "7-6 Spintop Nebula",
    0x606: "7-7 Star Haven",
    0x607: "7-8 Starfruit Garden",
    0x60e: "7-Tower: Electron Tower",
    0x618: "7-Castle: Novastar Castle",
    0x61e: "The Blue Switch Palace",
    0x620: "Challenge House F",
    0x625: "7-Airship: Spaceship Koopa",
    0x700: "8-1 Batallion Frontier",
    0x701: "8-2 Jet Airship",
    0x702: "8-4 Molten Airship",
    0x703: "8-3 Burnstone Flowfalls",
    0x704: "8-Train: Underground Railroad",
    0x705: "8-6 Volcano Rapids",
    0x706: "8-7 Magmaworks Factory",
    0x707: "8-A Dragonride Firesea",
    0x708: "8-8 Eruption Crater",
    0x709: "8-9 Ironworks Forge",
    0x70e: "8-Tower: Factory Tower",
    0x70f: "8-Tower-2: Pendulum Tower",
    0x717: "8-Castle: Bowser's Keep",
    0x718: "8-Castle-2: Bowser's Castle",
    0x720: "Challenge House G",
    0x800: "9-1 Red Lava",
    0x801: "9-2 Brown Forest",
    0x802: "9-3 Orange Prairie",
    0x803: "9-4 Yellow Beach",
    0x804: "9-5 Mossdeep Greens",
    0x805: "9-6 Blue Chilldesert",
    0x806: "9-7 Navyblue Molemine",
    0x807: "9-8 Purple Sewer",
    0x808: "9-9 Grey Mountains",
    0x809: "9-10 Black Clappers",
    0x900: "A-1 Autumn Plateau",
    0x901: "A-2 Appletree Woods",
    0x902: "A-3 Fall Harvest",
    0x903: "A-A Goldbuzz Forest",
    0x904: "A-Fortress: Leafpile Fortress",
    0x905: "B-1 Mighty Meadow",
    0x906: "B-2 Pintsized Plains",
    0x907: "B-3 Troopashell Track",
    0x908: "B-4 Cheepcheep Creek",
    0x909: "B-Fortress: Formmidable Fortress",
    0x90a: "D-1 Swooper Cellar",
    0x90b:"D-2 Toxic Wigglershaft",
    0x90c: "D-3 Spine Springs",
    0x90d: "D-A Carapace Catacomb",
    0x90e: "D-Fortress: Toxic Fortress",
    0x90f: "E-1 Bombshell Bridge",
    0x910: "E-2 Fallout Footbridge",
    0x911: "E-3 Bombassault Gorge",
    0x912: "C-1 Manta Raid",
    0x915: "C-2 Nimbus Highway",
    0x916: "C-3 Parabeetle Peril",
    0x917: "C-4 Sprocket Skies",
    0x918: "C-Tower: Clockwork Tower",
    0x91e: "The Red Switch Palace",
    0x921: "Challenge House H",
    0x922: "Minimega Music House",
    0x923: "Crystal Music House",
    0x924: "Goldwood Music House"
    
}


/* Save States
W1: A lot of W1
W1-2: A lot of RAM address finding
WA:
    1: Start
    2: Spring shenanigans
    3: Berries in A-2
    4: Music House


W2:
    1: 2-3
    2: Challenge House B
    3: 2-6
    4: Desert Music House
    5: chal-3
    6: music 3
    7: random
    8: after green palace
    9: Challenge House D
    10: in green palace

W4:
    1: Village Music House
    2: 2-Fortress boss
    3: 5-4 pick a path
    4: Red Switch
    5: 5-Tower boss
    6: Frosty Music House
    7: Challenge House E
    8: Haunted Music House
    9: blue switch
4-4 get 3rd star coin without green blocks
7-1: complete secret exit without blue switch
7-castle has 2 red rings

W8: 
    1: idk
    2: 8-tower
    3-6: Random stuff
    7: Rollercoaster level
    8: Outside Bowser's Keep
    9: Outside final boss

WB C D:
    Unordered
    8: Last stage in special world
Notes about coinless run
1-Tower 1 coin run
1-Airship seems like a good challenge
2-2 seems quite hard
2-7 is the sandstorm level, could be fun
3-7 seems challenging if propeller restricted
4-Tower minimum coin run without propeller?


*/






rich_presence_display("Stage {0} | Lives {1} | 💀 {2} | {3}",
    rich_presence_value("stage", byte(0xC7FE65)),
    rich_presence_value("lives", word(0x354E93)),
    rich_presence_value("death", tally(0, prev(byte(0x354E93)) > byte(0x354E93), always_false())),
    rich_presence_value("score", dword_be(0x1547D48), format="SCORE")
)

